Args = -H:+UnlockExperimentalVMOptions \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.hosted.layeredimage=ALL-UNNAMED \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.layeredimage=ALL-UNNAMED \
       -H:Features=example.micronaut.baselayer.ReflectArrayInitialLayerFeature \
       -H:LayerCreate=@layer-create.args \
       -H:+RelativeCodePointers \
       --initialize-at-run-time=java.lang.VirtualThread \
       --initialize-at-run-time=io.netty.buffer \
       --initialize-at-run-time=io.netty.channel \
       --initialize-at-run-time=io.netty.handler \
       --initialize-at-run-time=io.netty.resolver \
       --initialize-at-run-time=io.netty.util \
       --initialize-at-run-time=io.netty.bootstrap \
       -H:-UnlockExperimentalVMOptions

