Args = -H:+UnlockExperimentalVMOptions \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.hosted.layeredimage=ALL-UNNAMED \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.layeredimage=ALL-UNNAMED \
       -H:Features=example.micronaut.baselayer.ReflectArrayInitialLayerFeature \
       -H:LayerCreate=@layer-create.args \
       -H:ApplicationLayerOnlySingletons=io.micronaut.core.io.service.ServiceScanner$StaticServiceDefinitions \
       -H:ApplicationLayerInitializedClasses=io.micronaut.inject.annotation.AnnotationMetadataSupport \
       -H:ApplicationLayerInitializedClasses=io.micronaut.core.io.service.MicronautMetaServiceLoaderUtils \
       -H:+RelativeCodePointers \
       --initialize-at-run-time=io.netty.buffer \
       --initialize-at-run-time=io.netty.channel \
       --initialize-at-run-time=io.netty.handler \
       --initialize-at-run-time=io.netty.resolver \
       --initialize-at-run-time=io.netty.util \
       --initialize-at-run-time=io.netty.bootstrap \
       --initialize-at-run-time=java.sql.Date,java.sql.Time,java.sql.Timestamp \
       -H:-UnlockExperimentalVMOptions
